pipeline_space:
  # Learning rates: pick 5 values logarithmically spaced
  lr:
    type: categorical
    choices: [1e-5, 3e-5, 1e-4, 3e-4, 1e-3, 3e-3]
  
  random_allowed:
    type: categorical
    choices: [1, 5, 12]

  # Number of layers fixed
  num_layers: 4

  # Hidden dimensions
  hidden_dim: 128

  # Weight decay: 2 choices
  weight_decay:
    type: categorical
    choices: [0.0, 0.01]

  # Learning rate schedule
  lr_schedule: "cosine"

  # Training parameters
  epochs: 
    type: categorical
    choices: [0, 5, 10, 20]

  # Different subsets of context curves
  context_id: 0

  use_context: True
  batch_size: 96

optimizer: grid_search

# Maximum number of total evaluations (all combinations)
# max_evaluations_total: 70