pipeline_space:
  lr:
    type: categorical
    choices: [1e-5, 3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 1e-2, 3e-2, 1e-1]

  num_layers: 4
  hidden_dim:
    type: categorical
    choices: [128, 256, 512]
  weight_decay:
    type: categorical
    choices: [0.0, 0.0001, 0.001]
  epochs:
    type: int
    lower: 5
    upper: 50
    is_fidelity: true
  batch_size: 128
  use_context: false
optimizer: ifbo
max_evaluations_total: 30 # Total HPO

