pipeline_space:
  lr:
    type: categorical
    choices: [1e-4, 3e-4]

  num_layers:
    type: categorical
    choices: [2, 4, 6]  # depths

  hidden_dim:
    type: categorical
    choices: [128, 256, 512]  # width scaling

  weight_decay:
    type: categorical
    choices: [0.0, 1e-4, 1e-3]

  lr_schedule:
    type: categorical
    choices: ["none", "warmup", "cosine", "cooldown", "warmup+cooldown"]

  epochs: 150

  batch_size: 96

optimizer: grid_search
max_evaluations_total: 270
