pipeline_space:
  scale_pair:
    type: categorical
    choices: ["[14562560, 77124608]", "[32270848, 77124608]", "[77124608, 134561280]"]
  # shrink: [0.1, 0.2, 0.4]
  # tkpm: [10.0, 20.0, 30.0]
  observe_fraction:
    type: categorical
    choices: [0.2, 0.4, 0.6]

optimizer: grid_search

# Maximum number of total evaluations (all combinations)
# max_evaluations_total: 70

